// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mindly.Infrastructure.Persistence;

#nullable disable

namespace Mindly.Infrastructure.Migrations
{
    [DbContext(typeof(MindlyDbContext))]
    [Migration("20251112161533_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Mindly.Domain.Entities.BreakPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("BreakType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FocusSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("_durationMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DurationMinutes");

                    b.HasKey("Id");

                    b.HasIndex("FocusSessionId");

                    b.ToTable("BreakPeriods", (string)null);
                });

            modelBuilder.Entity("Mindly.Domain.Entities.DeviceSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FocusSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FocusSessionId");

                    b.ToTable("DeviceSignals", (string)null);
                });

            modelBuilder.Entity("Mindly.Domain.Entities.FocusSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("FocusMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("_actualDurationMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ActualDurationMinutes");

                    b.Property<int>("_plannedDurationMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PlannedDurationMinutes");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("FocusSessions", (string)null);
                });

            modelBuilder.Entity("Mindly.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkMode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("_dailyFocusGoalMinutes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DailyFocusGoalMinutes");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("Mindly.Domain.Entities.BreakPeriod", b =>
                {
                    b.HasOne("Mindly.Domain.Entities.FocusSession", null)
                        .WithMany("Breaks")
                        .HasForeignKey("FocusSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mindly.Domain.Entities.DeviceSignal", b =>
                {
                    b.HasOne("Mindly.Domain.Entities.FocusSession", null)
                        .WithMany("DeviceSignals")
                        .HasForeignKey("FocusSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mindly.Domain.Entities.FocusSession", b =>
                {
                    b.HasOne("Mindly.Domain.Entities.UserProfile", null)
                        .WithMany("Sessions")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mindly.Domain.Entities.FocusSession", b =>
                {
                    b.Navigation("Breaks");

                    b.Navigation("DeviceSignals");
                });

            modelBuilder.Entity("Mindly.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
